# Generated by Django 6.0.5 on 2026-06-04 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='如：2025-2026-1', max_length=20, unique=True, verbose_name='学期标识')),
                ('display_name', models.CharField(help_text='如：2025-2026学年第一学期', max_length=50, verbose_name='学期名称')),
            ],
            options={
                'verbose_name': '学期',
                'verbose_name_plural': '学期',
                'db_table': 'semester',
                'ordering': ['-name'],
            },
        ),
    ]
