# Generated by Django 6.0.5 on 2026-05-28 06:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResearchGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='教研组名称')),
            ],
            options={
                'verbose_name': '教研组',
                'verbose_name_plural': '教研组',
                'db_table': 'research_group',
            },
        ),
        migrations.CreateModel(
            name='TeacherProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_no', models.CharField(max_length=20, unique=True, verbose_name='工号')),
                ('realname', models.CharField(max_length=50, verbose_name='真实姓名')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='联系电话')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='邮箱')),
                ('address', models.CharField(blank=True, max_length=200, verbose_name='家庭住址')),
            ],
            options={
                'verbose_name': '老师简介',
                'verbose_name_plural': '老师简介',
                'db_table': 'teacher_profile',
            },
        ),
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stu_no', models.CharField(max_length=20, unique=True, verbose_name='学号')),
                ('realname', models.CharField(max_length=50, verbose_name='真实姓名')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='联系电话')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='邮箱')),
                ('address', models.CharField(blank=True, max_length=200, verbose_name='家庭住址')),
                ('class_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='classes.classes', verbose_name='所在班级')),
            ],
            options={
                'verbose_name': '学生简介',
                'verbose_name_plural': '学生简介',
                'db_table': 'student_profile',
            },
        ),
    ]
