# Generated by Django 6.0.5 on 2026-05-28 08:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classes', '0002_initial'),
        ('research_group', '0001_initial'),
        ('user_profile', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='class_ids',
            field=models.ManyToManyField(blank=True, related_name='teachers', to='classes.classes', verbose_name='所教班级'),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='research_groups',
            field=models.ManyToManyField(blank=True, related_name='teachers', to='research_group.researchgroup', verbose_name='所属教研组'),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_profile', to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
    ]
