# Generated by Django 6.0.5 on 2026-06-04 06:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('semester_dict', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='考试名称')),
                ('exam_type', models.CharField(choices=[('MONTHLY', '月考'), ('MOCK', '模拟考'), ('MIDTERM', '期中'), ('FINAL', '期末')], max_length=20, verbose_name='考试类型')),
                ('exam_date', models.DateField(verbose_name='考试日期')),
                ('grade', models.CharField(choices=[('GRADE_1', '一年级'), ('GRADE_2', '二年级'), ('GRADE_3', '三年级'), ('GRADE_4', '四年级'), ('GRADE_5', '五年级'), ('GRADE_6', '六年级'), ('GRADE_7', '七年级'), ('GRADE_8', '八年级'), ('GRADE_9', '九年级'), ('SENIOR_1', '高一'), ('SENIOR_2', '高二'), ('SENIOR_3', '高三')], max_length=20, verbose_name='所属年级')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exams', to='semester_dict.semester', verbose_name='所属学期')),
            ],
            options={
                'verbose_name': '考试计划',
                'verbose_name_plural': '考试计划',
                'db_table': 'exam_plan',
                'ordering': ['-exam_date', 'grade'],
            },
        ),
    ]
