# Generated by Django 6.0.5 on 2026-06-04 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examplan',
            name='name',
            field=models.CharField(blank=True, max_length=200, verbose_name='考试名称'),
        ),
    ]
