# Generated by Django 6.0.5 on 2026-05-22 05:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('grade', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='班级名称')),
                ('code', models.CharField(blank=True, max_length=20, verbose_name='班级编码')),
                ('capacity', models.PositiveIntegerField(default=0, verbose_name='班级容量')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='classes', to='grade.grade', verbose_name='所属年级')),
                ('homeroom_teacher', models.ForeignKey(blank=True, limit_choices_to={'role': 'TEACHER'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_classes', to=settings.AUTH_USER_MODEL, verbose_name='班主任')),
            ],
            options={
                'verbose_name': '班级',
                'verbose_name_plural': '班级',
                'ordering': ['grade__sort_order', 'grade_id', 'name'],
                'constraints': [models.UniqueConstraint(fields=('grade', 'name'), name='unique_class_name_per_grade')],
            },
        ),
    ]
