# Generated by Django 6.0.5 on 2026-05-28 08:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classes', '0001_initial'),
        ('user_profile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='classes',
            name='headmaster',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='headmaster_classes', to='user_profile.teacherprofile', verbose_name='班主任'),
        ),
        migrations.AddConstraint(
            model_name='classes',
            constraint=models.UniqueConstraint(fields=('grade', 'name'), name='unique_grade_class'),
        ),
    ]
