# Generated by Django 6.0.5 on 2026-05-28 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ResearchGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='教研组名称')),
            ],
            options={
                'verbose_name': '教研组',
                'verbose_name_plural': '教研组',
                'db_table': 'research_group',
            },
        ),
    ]
