# Generated by Django 6.0.5 on 2026-06-04 06:36

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exam', '0001_initial'),
        ('subjects', '0002_seed_subjects'),
        ('user_profile', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.DecimalField(decimal_places=1, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(999.9)], verbose_name='分数')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='exam.examplan', verbose_name='考试')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='user_profile.studentprofile', verbose_name='学生')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='scores', to='subjects.subjects', verbose_name='科目')),
            ],
            options={
                'verbose_name': '成绩记录',
                'verbose_name_plural': '成绩记录',
                'db_table': 'score',
                'ordering': ['exam', 'student', 'subject'],
                'constraints': [models.UniqueConstraint(fields=('student', 'exam', 'subject'), name='unique_student_exam_subject')],
            },
        ),
    ]
