# Generated by Django 6.0.5 on 2026-06-04 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClassDict',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(choices=[('GRADE_1', '一年级'), ('GRADE_2', '二年级'), ('GRADE_3', '三年级'), ('GRADE_4', '四年级'), ('GRADE_5', '五年级'), ('GRADE_6', '六年级'), ('GRADE_7', '七年级'), ('GRADE_8', '八年级'), ('GRADE_9', '九年级'), ('SENIOR_1', '高一'), ('SENIOR_2', '高二'), ('SENIOR_3', '高三')], max_length=20, verbose_name='年级')),
                ('name', models.CharField(max_length=50, verbose_name='班级名称')),
            ],
            options={
                'verbose_name': '班级',
                'verbose_name_plural': '班级',
                'db_table': 'dict_class',
                'ordering': ['grade', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ResearchGroupDict',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='教研组名称')),
            ],
            options={
                'verbose_name': '教研组',
                'verbose_name_plural': '教研组',
                'db_table': 'dict_research_group',
            },
        ),
        migrations.CreateModel(
            name='SemesterDict',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='如：2025-2026-1', max_length=20, unique=True, verbose_name='学期标识')),
                ('display_name', models.CharField(help_text='如：2025-2026学年第一学期', max_length=50, verbose_name='学期名称')),
            ],
            options={
                'verbose_name': '学期',
                'verbose_name_plural': '学期',
                'db_table': 'dict_semester',
                'ordering': ['-name'],
            },
        ),
        migrations.CreateModel(
            name='SubjectDict',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='科目名称')),
            ],
            options={
                'verbose_name': '科目',
                'verbose_name_plural': '科目',
                'db_table': 'dict_subject',
            },
        ),
    ]
